---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapp
  labels:
    app: backendapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
      - name: backendapp
        image: reeceelder/backend:latest
        imagePullPolicy: Always
        env:
        - name: db_endpoint
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: db_endpoint
        - name: password
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: password
        - name: db_username
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: db_username
        - name: testdb_username
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: testdb_username
        - name: testdb_endpoint
          valueFrom:
            secretKeyRef:
              name: secretvar
              key: testdb_endpoint
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: backendip
  labels:
    app: backendapp
spec:
  selector:
    app: backendapp
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
