---
- hosts: testvm
  become: true
  vars:
    CTOP_VERSION: "0.7.3"
    DOCKER_COMPOSE_VERSION: "1.25.1"
    DOCKER_PACKAGES:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    USER: "ubuntu"
  roles:
  - utilities
  - sudo-doers
  - node
  - docker
  - docker-compose


- hosts: jenkins
  become: true
  vars:
    CTOP_VERSION: "0.7.3"
    DOCKER_COMPOSE_VERSION: "1.25.1"
    DOCKER_PACKAGES:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    USER: "ubuntu"
  roles:
  - utilities
  - jenkins
  - kubernetes
  - sudo-doers
  - docker
  - docker-compose

  handlers:
  - name: Restart docker
    service:
      name: docker
      state: restarted


